import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import pub from '../public/assets/images/pub.png'
import Navigation from '../components/global_components/navigation/Navigation'
import Title from '../components/global_components/title/Title'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img src={pub.src} alt="pub" />
        <div className={styles.main_container}>
            <Title>TOP CATÉGORIES</Title>
            <Navigation/>
        </div>
      </main>
    </div>
  )
}
